services:
  app:
    container_name: kata-game-of-life
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: node dist/index.js
    environment:
      - NODE_ENV=development
